## Setup

In [1]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "nlp"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

Let's load pretrained OpenAI's GPT model

In [3]:
from transformers import TFOpenAIGPTLMHeadModel

model = TFOpenAIGPTLMHeadModel.from_pretrained("openai-gpt")

All model checkpoint layers were used when initializing TFOpenAIGPTLMHeadModel.

All the layers of TFOpenAIGPTLMHeadModel were initialized from the model checkpoint at openai-gpt.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predictions without further training.


In [4]:
from transformers import OpenAIGPTTokenizer

tokenizer = OpenAIGPTTokenizer.from_pretrained("openai-gpt")

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


In [5]:
prompt_text = "This royal throne of kings, this sceptred isle"
encoded_prompt = tokenizer.encode(prompt_text,
                                 add_special_tokens=False,
                                 return_tensors="tf")
encoded_prompt

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187]])>

In [7]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences)

generated_sequences

<tf.Tensor: shape=(5, 50), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,  1259,  2150,   664,   725,   239, 40477,  1076,  1460,
          641,  1374,   239,  3491,   240,   481,   618,   509,  1374,
          239,   616,   544,   895,   481,  2676,  2814,   811,   239,
          895,   557,   246,  2021,   481,  4815,  1246,   481, 32661,
          485,   513,  7759,   488,   481],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   240,   616, 21719,   240,   616,  1440,  2878,  2278,
         1218,   239,   557,   512,   699,   240,   481,  2873,   498,
          704,  1424,   488,  9690, 28520,   544,   504,   704,  1934,
          239,   587,   595,   925,   246,  3806,   240,   547,   945,
          239,   587,   595,   851,  1288],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   244, 40477,   562,   531,  4087,   487,   636,
          604

In [10]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_spaces=True)
    print(text)
    print("-"*80)

this royal throne of kings, this sceptred isle must become no more. 
 those days were gone. indeed, the king was gone. this is why the magic wore off. why as a child the princess gave the scepter to her guardian and the
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle, this oasis, this past seven hundred years. as you know, the weight of your great and glorious exploits is on your shoulders. do not make a mistake, my son. do not let these
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. " 
 for an instant he would have liked to indulge in another spell, to come to the full senses of his old age and start following her every whim. but his pride had prevented him from
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle, or even suidhe. " he hesitated, and s